[tool.ruff]
ignore = [
    "PLR09",
    "PLR2004",
]

select = [
    "F",
    "W",
    "E",
    "I",
    "A",
    "B",
    "C4",
    "SIM",
    "UP",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "RUF",
    "TRY3",
]

[tool.ruff.per-file-ignores]
"docs/source/conf.py" = ["A001"]
